coverage:
  range: 50..90
  round: down
  precision: 2

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 20%
