coverage:
  range: 50..90
  round: down
  precision: 2

  ignore:
    - "examples"
    - "test"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 20%

comment: false

github_checks:
    annotations: false

codecov:
  token: fc902be7-5dcf-47f7-ab94-9d773c5b27d7