# this include allows us to reference defaults in anl/ci-resource/defaults
include:
  - project: 'anl/ci-resources/defaults'
    ref: main
    file:
      - '/runners.yml'

stages:
  - ci # stages may have any name

# the below submits a batch job to the scheduler
submit_batch: # CI jobs may have any name
  stage: ci  # from the stages list above
  extends: .aurora-batch-runner # this includes the defaults provided in the 'anl/ci-resources/defaults' project
  variables:  # scheduler parameters must be included, adjust the below to match your values
    ANL_AURORA_SCHEDULER_PARAMETERS: "-A Julia -l select=1,walltime=10:00,filesystems=home:flare -q debug"
    JULIA_DEPOT_PATH: "/lus/flare/projects/Julia/mschanen/julia_depot_path"
  script:
    - id
    - hostname
    - echo "Running on $(hostname) with setuid shell runner"
    - export JULIA
    - /home/mschanen/.local/bin/julia-lts --project -e 'using Pkg; Pkg.update()'
    - /home/mschanen/.local/bin/julia-lts --project test/test-oneapi.jl
