env:
  JULIA_VERSION: "1.10.10"
  BUILDKITE_HOME: "/var/lib/buildkite-agent"
  JULIA_DEPOT_PATH: "$BUILDKITE_HOME/.julia-oceananigans"
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  XLA_REACTANT_GPU_PREALLOCATE: false
  OCEANANIGANS_DIR: "$HOME/Oceananigans.jl-$BUILDKITE_BUILD_NUMBER"

agents:
  queue: "Oceananigans"
with:
  coverage: false

steps:
  - label: "ðŸ•ï¸ initialize environment"
    key: "init"
    agents:
      queue: "Oceananigans-nautilus"
    env:
      TEST_GROUP: "init"
    command: |
      juliaup add $JULIA_VERSION

      mkdir -p "$OCEANANIGANS_DIR"
      rsync -a . "$OCEANANIGANS_DIR/"
      cd "$OCEANANIGANS_DIR"

      # Force CubedSphere to PR #41 branch (or replace rev with exact SHA)
      julia --color=yes --project=. -e 'using Pkg; println("Active project before activate: ", Base.active_project()); Pkg.activate("."); println("Active project after activate: ", Base.active_project()); try Pkg.rm("CubedSphere"); catch e; @info("Pkg.rm(CubedSphere) skipped", e); end; Pkg.add(PackageSpec(name="CubedSphere", url="https://github.com/CliMA/CubedSphere.jl", rev="sb/non-uniform-conformal-mapping")); Pkg.resolve(); Pkg.instantiate(); deps = Pkg.dependencies(); cs = first(filter(x -> last(x).name == "CubedSphere", collect(deps))); println("\n--- CubedSphere manifest entry ---"); println(cs); println("----------------------------------\n"); Pkg.status(; mode=Pkg.PKGMODE_MANIFEST)'
      # Now run init tests
      julia +$JULIA_VERSION -O0 --color=yes --project -e 'using Pkg; Pkg.test()'
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "{{ matrix.architecture }} - {{ matrix.group }} tests"
    key: "tests"
    depends_on: "init"
    agents:
      queue: "Oceananigans-nautilus"
    command: |
      # Add matrix-specific environment variables
      if [[ "{{ matrix.architecture }}" == "CPU" ]]; then
        export CUDA_VISIBLE_DEVICES="-1"
        export TEST_ARCHITECTURE="CPU"
      else
        export CUDA_VISIBLE_DEVICES="0"
        export TEST_ARCHITECTURE="GPU"
      fi

      # Force IFRT runtime for Reactant (this can be moved to Project.toml on 1.11)
      touch LocalPreferences.toml
      echo "[Reactant]" >> LocalPreferences.toml
      echo "xla_runtime = \"IFRT\"" >> LocalPreferences.toml
      cat LocalPreferences.toml

      # Strip emoji for environment variable
      group="{{ matrix.group }}"
      export TEST_GROUP="\${{group#* }}"
      echo $TEST_GROUP

      # Run tests
      cd "$OCEANANIGANS_DIR"
      # Force CubedSphere branch before tests
      julia --color=yes --project=. -e 'using Pkg; println("Active project before activate: ", Base.active_project()); Pkg.activate("."); println("Active project after activate: ", Base.active_project()); try Pkg.rm("CubedSphere"); catch e; @info("Pkg.rm(CubedSphere) skipped", e); end; Pkg.add(PackageSpec(name="CubedSphere", url="https://github.com/CliMA/CubedSphere.jl", rev="sb/non-uniform-conformal-mapping")); Pkg.resolve(); Pkg.instantiate(); deps = Pkg.dependencies(); cs = first(filter(x -> last(x).name == "CubedSphere", collect(deps))); println("\n--- CubedSphere manifest entry ---"); println(cs); println("----------------------------------\n"); Pkg.status(; mode=Pkg.PKGMODE_MANIFEST)'
      julia +$JULIA_VERSION -O0 --color=yes --project -e 'using Pkg; Pkg.test()'

    matrix:
      setup:
        architecture:
          - "CPU"
          - "GPU"
        group:
          - "ðŸ‡ unit"
          - "ðŸ‘» abstract_operations"
          - "ðŸ•Š poisson_solvers_1"
          - "ðŸ¦– poisson_solvers_2"
          - "ðŸ¦¤ general_solvers"
          - "ðŸŽ£ turbulence_closures"
          - "ðŸ¦€ time_stepping_1"
          - "ðŸ¦ˆ time_stepping_2"
          - "ðŸ¦Ÿ time_stepping_3"
          - "ðŸ« nonhydrostatic_regression"
          - "ðŸ™ hydrostatic_free_surface"
          - "ðŸ« tripolar_grid"
          - "ðŸ¥‘ vertical_coordinate"
          - "ðŸ™ˆ hydrostatic_regression"
          - "ðŸ¦¢ shallow_water"
          - "ðŸ³ simulation"
          - "ðŸ‚ lagrangian_particles"
          - "ðŸ§… multi_region"
          - "ðŸ¦§ scripts"
          - "ðŸ‘º enzyme"
          - "ðŸ‘¹ reactant_1"
          - "ðŸŽ­ reactant_2"
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  #####
  ##### Documentation
  #####

  - label: "ðŸ¦‰ documentation"
    depends_on: "init"
    agents:
      queue: "Oceananigans-nautilus"
    env:
      CUDA_VISIBLE_DEVICES: "0" # GPU for docs
    command: |
      cd "$OCEANANIGANS_DIR"
      # Force CubedSphere in docs environment too
      julia --color=yes --project=docs/ -e 'using Pkg; println("Active project before activate: ", Base.active_project()); Pkg.activate("docs"); println("Active project after activate: ", Base.active_project()); try Pkg.rm("CubedSphere"); catch e; @info("Pkg.rm(CubedSphere) skipped", e); end; Pkg.add(PackageSpec(name="CubedSphere", url="https://github.com/CliMA/CubedSphere.jl", rev="sb/non-uniform-conformal-mapping")); Pkg.resolve(); Pkg.instantiate(); deps = Pkg.dependencies(); cs = first(filter(x -> last(x).name == "CubedSphere", collect(deps))); println("\n--- CubedSphere (docs) manifest entry ---"); println(cs); println("----------------------------------\n"); Pkg.status(; mode=Pkg.PKGMODE_MANIFEST)'
      julia +$JULIA_VERSION --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      julia +$JULIA_VERSION --color=yes --project=docs/ docs/make.jl

  #####
  ##### Blocking wait on tests and documentation
  #####

  - wait: ~
    continue_on_failure: true

  #####
  ##### Clean up
  #####

  - label: "ðŸ§¹ clean up environment"
    agents:
      queue: "Oceananigans-nautilus"
    commands:
      - "test -d $OCEANANIGANS_DIR && du -hs $OCEANANIGANS_DIR || true"
      - "test -d $OCEANANIGANS_DIR && rm -rf $OCEANANIGANS_DIR || true"
