env:
  XLA_REACTANT_GPU_PREALLOCATE: false
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  JULIA_NUM_PRECOMPILE_TASKS: 4
  JULIA_NUM_THREADS: 4

steps:
  - label: "🦕 AMDGPU extension tests - Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.12"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
    command: |
      julia --project=test/extensions -O0 --color=yes -e 'using Pkg; Pkg.instantiate()'

      TEST_GROUP=init    julia --project=test/extensions -O0 --color=yes test/runtests.jl
      TEST_GROUP=amdgpu  julia --project=test/extensions -O0 --color=yes test/runtests.jl
    agents:
      queue: "juliagpu"
      rocm: "*"
    timeout_in_minutes: 30
    soft_fail:
      - exit_status: 3


  - label: "🦖 oneAPI extension tests - Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.12"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
    command: |
      julia --project=test/extensions -O0 --color=yes -e 'using Pkg; Pkg.instantiate()'

      TEST_GROUP=init    julia --project=test/extensions -O0 --color=yes test/runtests.jl
      TEST_GROUP=oneapi  julia --project=test/extensions -O0 --color=yes test/runtests.jl
    agents:
      queue: "juliagpu"
      intel: "*"
    timeout_in_minutes: 30
    soft_fail:
      - exit_status: 3
