env:
  JULIA_VERSION: "1.12.2"
  JULIA_VERSION_ENZYME: "1.10.10"
  BUILDKITE_HOME: "/var/lib/buildkite-agent"
  JULIA_DEPOT_PATH: "$BUILDKITE_HOME/.julia-oceananigans"
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  XLA_REACTANT_GPU_PREALLOCATE: false
  OCEANANIGANS_DIR: "$HOME/Oceananigans.jl-$BUILDKITE_BUILD_NUMBER"

agents:
  queue: "Oceananigans"
with:
  coverage: false

steps:
  - label: "🏕️ initialize general environment"
    key: "init"
    agents:
      queue: "Oceananigans-nautilus"
    env:
      TEST_GROUP: "init"
    command: |
      juliaup add $JULIA_VERSION

      mkdir -p "$OCEANANIGANS_DIR"
      rsync -a . "$OCEANANIGANS_DIR/"
      cd "$OCEANANIGANS_DIR"

      julia +$JULIA_VERSION -O0 --color=yes --project -e 'using Pkg; Pkg.Registry.update()'

      echo "--------------------"
      ls -lhrt
      echo "--------------------"
      rm -fv Manifest.toml
      echo "--------------------"
      ls -lhrt
      echo "--------------------"

      julia +$JULIA_VERSION -O0 --color=yes --project -e 'using Pkg; Pkg.test()'
      # After we have instantiated the general environment, move manifest to the
      # version-specific filename, not to clash with the manifest for Enzyme.
      mv -v Manifest.toml Manifest-v$(echo "${JULIA_VERSION}" | cut -d. -f1-2).toml
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🏕️ initialize enzyme environment"
    key: "init_enzyme"
    depends_on: "init"
    agents:
      queue: "Oceananigans-nautilus"
    env:
      TEST_GROUP: "init"
    command: |
      juliaup add $JULIA_VERSION_ENZYME
      cd "$OCEANANIGANS_DIR"

      julia +$JULIA_VERSION_ENZYME -O0 --color=yes --project -e 'using Pkg; Pkg.test()'
      # After we have instantiated the Enzyme environment, move manifest to the
      # version-specific filename, not to clash with the general manifest.
      # mv -v Manifest.toml Manifest-v$(echo "${JULIA_VERSION_ENZYME}" | cut -d. -f1-2).toml
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🦉 documentation"
    depends_on: "init"
    agents:
      queue: "Oceananigans-nautilus"
    env:
      CUDA_VISIBLE_DEVICES: "0" # GPU for docs
    command: |
      cd "$OCEANANIGANS_DIR"
      julia +$JULIA_VERSION --color=yes --project=docs/ -e \
        'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      julia +$JULIA_VERSION --color=yes --project=docs/ docs/make.jl

  - label: "{{ matrix.architecture }} - {{ matrix.group }} tests"
    key: "tests"
    depends_on: "init"
    agents:
      queue: "Oceananigans-nautilus"
    command: |
      # Add matrix-specific environment variables
      if [[ "{{ matrix.architecture }}" == "CPU" ]]; then
        export CUDA_VISIBLE_DEVICES="-1"
        export TEST_ARCHITECTURE="CPU"
      else
        export CUDA_VISIBLE_DEVICES="0"
        export TEST_ARCHITECTURE="GPU"
      fi

      # Strip emoji for environment variable
      group="{{ matrix.group }}"
      export TEST_GROUP="\${group#* }"
      echo $TEST_GROUP

      # Run tests
      cd "$OCEANANIGANS_DIR"
      julia +$JULIA_VERSION -O0 --color=yes --project -e 'using Pkg; Pkg.test()'

    matrix:
      setup:
        architecture:
          - "CPU"
          - "GPU"
        group:
          - "🦖 poisson_solvers_2"
          - "🐇 unit"
          - "👻 abstract_operations"
          - "🕊 poisson_solvers_1"
          - "🦤 general_solvers"
          - "🎣 turbulence_closures"
          - "🦀 time_stepping_1"
          - "🦈 time_stepping_2"
          - "🦟 time_stepping_3"
          - "🐫 nonhydrostatic_regression"
          - "🐙 hydrostatic_free_surface"
          - "🫐 tripolar_grid"
          - "🥑 vertical_coordinate"
          - "🙈 hydrostatic_regression"
          - "🦢 shallow_water"
          - "🐳 simulation"
          - "🍂 lagrangian_particles"
          - "🧅 multi_region"
          - "🦧 scripts"
          - "🍱 xesmf"

    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "{{ matrix.architecture }} - {{ matrix.group }} tests"
    key: "tests_enzyme_reactant"
    depends_on: "init_enzyme"
    agents:
      queue: "Oceananigans-nautilus"
    command: |
      # Add matrix-specific environment variables
      if [[ "{{ matrix.architecture }}" == "CPU" ]]; then
        export CUDA_VISIBLE_DEVICES="-1"
        export TEST_ARCHITECTURE="CPU"
      else
        export CUDA_VISIBLE_DEVICES="0"
        export TEST_ARCHITECTURE="GPU"
      fi

      # Strip emoji for environment variable
      group="{{ matrix.group }}"
      export TEST_GROUP="\${group#* }"
      echo $TEST_GROUP

      # Run tests
      cd "$OCEANANIGANS_DIR"
      julia +$JULIA_VERSION_ENZYME -O0 --color=yes --project -e 'using Pkg; Pkg.test()'

    matrix:
      setup:
        architecture:
          - "CPU"
          - "GPU"
        group:
          - "🎭 reactant_2"
          - "👺 enzyme"
          - "👹 reactant_1"

    retry:
      automatic:
        - exit_status: 1
          limit: 1
  #####
  ##### Blocking wait on tests and documentation
  #####

  - wait: ~
    continue_on_failure: true

  #####
  ##### Clean up
  #####

  - label: "🧹 clean up environment"
    agents:
      queue: "Oceananigans-nautilus"
    commands:
      - "test -d $OCEANANIGANS_DIR && du -hs $OCEANANIGANS_DIR || true"
      - "test -d $OCEANANIGANS_DIR && rm -rf $OCEANANIGANS_DIR || true"
