env:
  JULIA_VERSION: "1.10.9"
  JULIA_MINOR_VERSION: "1.10"
  TARTARUS_HOME: "/storage5/buildkite-agent"
  JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  JULIA_NUM_PRECOMPILE_TASKS: 24
  JULIA_NUM_THREADS: 8
  NSYS: "/storage6/nsight/bin/nsys"
  CUDA_VISIBLE_DEVICES: "1" # Tartarus device for GPU Benchmarking
  TMPDIR: "$TARTARUS_HOME/tmp"

steps:
  - label: "ðŸ•ï¸ initialize tartarus environment"
    key: "init"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "init"
      JULIA_BINDIR: "$TARTARUS_HOME/julia-$JULIA_VERSION/bin"
    command: |
      # Download julia binaries
      wget -N -P $TARTARUS_HOME https://julialang-s3.julialang.org/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_VERSION-linux-x86_64.tar.gz
      tar xf $TARTARUS_HOME/julia-$JULIA_VERSION-linux-x86_64.tar.gz -C $TARTARUS_HOME
    agents:
      queue: "Oceananigans-benchmarks"
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - wait

  # Saving the latest build ID of the main branch for
  # later comparison of the artifacts in PRs
  - label: "ðŸ’¾ conditional metadata save" 
    key: "save-metadata"
    agents:
      queue: Oceananigans-benchmarks
    
    command: |
      if [ "$BUILDKITE_BRANCH" = "main" ]; then
        echo "Saving build ID for main..."
        buildkite-agent meta-data set "latest-main-build-number" "$BUILDKITE_BUILD_NUMBER"
        buildkite-agent meta-data set "latest-main-job-number"   "$BUILDKITE_JOB_ID"
      else
        echo "Not on main, skipping metadata save."
      fi
    
  - label: "ðŸš€ Oceananigans GPU benchmarks"
    key: "benchmarks"
    agents:
      queue: "Oceananigans-benchmarks"

    command: |
      # Instantiate
      # $TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project --check-bounds=no -e 'using Pkg; Pkg.instantiate()'

      # # Run Periodic benchmarks
      # export BENCHMARK_GROUP="periodic"
      # $NSYS profile --output=periodic_output --trace=cuda $TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project --check-bounds=no test/benchmark_tests.jl
      # $NSYS stats periodic_output.nsys-rep > 
      echo "ciao" > periodic_output.txt

      # # Remove generated output files
      # rm periodic_output.nsys-rep
      # rm periodic_output.sqlite

      # # Run Bounded benchmarks
      # export BENCHMARK_GROUP="bounded"
      # $NSYS profile --output=bounded_output --trace=cuda $TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project --check-bounds=no test/benchmark_tests.jl
      # $NSYS stats bounded_output.nsys-rep > bounded_output.txt
      echo "ciao" > bounded_output.txt
      
      # # Remove generated output files
      # rm bounded_output.nsys-rep
      # rm bounded_output.sqlite

      # # Run Periodic cheap advection benchmarks
      # export BENCHMARK_GROUP="periodic_cheap_advection"
      # $NSYS profile --output=periodic_cheap_advection_output --trace=cuda $TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project --check-bounds=no test/benchmark_tests.jl
      # $NSYS stats periodic_cheap_advection_output.nsys-rep > periodic_cheap_advection_output.txt

      # # Remove generated output files
      # rm periodic_cheap_advection_output.nsys-rep
      # rm periodic_cheap_advection_output.sqlite

      # # Run Bounded cheap advection benchmarks
      # export BENCHMARK_GROUP="bounded_cheap_advection"
      # $NSYS profile --output=bounded_cheap_advection_output --trace=cuda $TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project --check-bounds=no test/benchmark_tests.jl
      # $NSYS stats bounded_cheap_advection_output.nsys-rep > bounded_cheap_advection_output.txt

      # # Remove generated output files
      # rm bounded_cheap_advection_output.nsys-rep
      # rm bounded_cheap_advection_output.sqlite

      # # Run Immersed benchmarks
      # export BENCHMARK_GROUP="immersed"
      # $NSYS profile --output=immersed_output --trace=cuda $TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project --check-bounds=no test/benchmark_tests.jl
      # $NSYS stats immersed_output.nsys-rep > immersed_output.txt

      # # Remove generated output files
      # rm immersed_output.nsys-rep
      # rm immersed_output.sqlite

    artifact_paths:
      - "periodic_output.txt"
      - "bounded_output.txt"
      - "periodic_cheap_advection_output.txt"
      - "bounded_cheap_advection_output.txt"
      - "immersed_output.txt"
    soft_fail:
      - exit_status: 3

  - label: "â¬‡ Fetch and compare with main"
    key: "fetch-compare"
    agents:
      queue: "Oceananigans-benchmarks"

    command: |
      # First we donwload the artifacts from the current PR build
      buildkite-agent artifact download "*.txt" .

      export MAIN_BUILD_NUM=45 # $(buildkite-agent meta-data get "latest-main-build-number")
      export MAIN_BUILD_JOB=01966378-3b39-42b4-b65b-0af1a9b04892 # $(buildkite-agent meta-data get "latest-main-job-number")

      echo $MAIN_BUILD_NUM
      echo $MAIN_BUILD_JOB
      
      # Then we fetch the artifacts from the main branch build
      curl -s -H "Authorization: Bearer ${BUILDKITE_API_TOKEN}" \
        "https://api.buildkite.com/v2/organizations/clima/pipelines/oceananigans-benchmarks-1/builds/${MAIN_BUILD_NUM}/jobs/${MAIN_BUILD_JOB}/artifacts" \
        -o artifacts.json

      echo "ðŸ” artifacts.json contents:"
      cat artifacts.json

      # Comparing the artifacts, creating the diff files and uploading them
      for file in $(jq -r '.[] | select(.filename | endswith(".txt")) | .filename' artifacts.json); do
        echo "Downloading ${file} from main..."
        url=$(jq -r --arg filename "${file}" '.[] | select(.filename == ${filename}) | .download_url' artifacts.json)
        curl -s -L "$url" -o "baseline_${file}"

        echo "Comparing $file with baseline..."
        if [ -f "${file}" ]; then
          diff -u "baseline_$file" "${file}" > "diff_${file}" || true
        else
          echo "${file} not found in PR build. Skipping diff." > "diff_${file}"
        fi
      done

      echo "Uploading diffs..."
      buildkite-agent artifact upload "diff_*.txt"

      echo "Annotating summary..."
      for diff in diff_*.txt; do
        buildkite-agent annotate --style info --context "${diff}" < "${diff}"
      done