env:
  JULIA_VERSION: "1.5.2"
  JULIA_MINOR_VERSION: "1.5"
  SVERDRUP_HOME: "/data5/glwagner"
  TARTARUS_HOME: "/var/lib/buildkite-agent"

steps:
  - label: "🎪 initialize gpu environment"
    key: "init_gpu"
    env:
      JULIA_DEPOT_PATH: "$SVERDRUP_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "init"
    commands:
      # Download julia binaries
      - "wget -N -P $SVERDRUP_HOME https://julialang-s3.julialang.org/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
      - "tar xf $SVERDRUP_HOME/julia-$JULIA_VERSION-linux-x86_64.tar.gz -C $SVERDRUP_HOME"

      # Instantiate and precompile 
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate(; verbose=true)'"
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.precompile()'"
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.status()'"

      # Force the initialization of the CUDA runtime as it is lazily loaded by default
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using CUDA; CUDA.versioninfo()'"

      # Download artifacts by running an empty testgroup and thereby executing /test/runtests.jl
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: GPU

  - label: "🏕️ initialize cpu environment"
    key: "init_cpu"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "init"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      # Download julia binaries
      - "wget -N -P $TARTARUS_HOME https://julialang-s3.julialang.org/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
      - "tar xf $TARTARUS_HOME/julia-$JULIA_VERSION-linux-x86_64.tar.gz -C $TARTARUS_HOME"

      # Instantiate, precompile, and download artifacts by running an empty testgroup and thereby executing /test/runtests.jl
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate(; verbose=true)'"
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.precompile()'"
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.status()'"
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: CPU

#####
##### Unit tests
#####

  - label: "🐀 gpu unit tests"
    env:
      TEST_GROUP: "unit"
    commands:
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: GPU
    depends_on: "init_gpu"

  - label: "🐇 cpu unit tests"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "unit"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"

#####
##### Model and time stepping (part 1)
#####

  - label: "🦀 gpu time stepping tests 1"
    env:
      TEST_GROUP: "time_stepping_1"
    commands:
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: GPU
    depends_on: "init_gpu"

  - label: "🦞 cpu time stepping tests 1"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "time_stepping_1"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"

#####
##### Model and time stepping (part 2)
#####

  - label: "🦈 gpu time stepping tests 2"
    env:
      TEST_GROUP: "time_stepping_2"
    commands:
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: GPU
    depends_on: "init_gpu"

  - label: "🐬 cpu time stepping tests 2"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "time_stepping_2"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"

#####
##### Simulation
#####

  - label: "🐳 gpu simulation tests"
    env:
      JULIA_DEPOT_PATH: "$SVERDRUP_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "simulation"
    commands:
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: GPU
    depends_on: "init_gpu"

  - label: "🐋 cpu simulation tests"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "simulation"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"

#####
##### Regression
#####

  - label: "🐫 gpu regression tests"
    env:
      JULIA_DEPOT_PATH: "$SVERDRUP_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "regression"
    commands:
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: GPU
    depends_on: "init_gpu"

  - label: "🐪 cpu regression tests"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "regression"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"

#####
##### Scripts
#####

  - label: "🦧 gpu scripts"
    env:
      JULIA_DEPOT_PATH: "$SVERDRUP_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "scripts"
    commands:
      - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: GPU'
    depends_on: "init_gpu"

  - label: "🦍 cpu scripts"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      TEST_GROUP: "scripts"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"

  # - label: "🦖 🦕 convergence tests"
  #   env:
  #     TEST_GROUP: "convergence"
  #   commands:
  #     - "$SVERDRUP_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
  #   agents:
  #     queue: Oceananigans
  #     architecture: CPU
  #   depends_on: "init_cpu"
  
#####
##### Documentation
#####

  - label: "🦉 documentation"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
    commands:
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'"
      - "$TARTARUS_HOME/julia-$JULIA_VERSION/bin/julia --color=yes --project=docs/ docs/make.jl"
    agents:
      queue: Oceananigans
      architecture: CPU
    depends_on: "init_cpu"

  - wait: ~
    continue_on_failure: true

#####
##### Clean up
#####

  - label: "🧻 clean up gpu environment"
    env:
      JULIA_DEPOT_PATH: "$SVERDRUP_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
    commands:
      - "rm -rf $JULIA_DEPOT_PATH"
    agents:
      queue: Oceananigans
      architecture: GPU

  - label: "🧹 clean up cpu environment"
    env:
      JULIA_DEPOT_PATH: "$TARTARUS_HOME/.julia-$BUILDKITE_BUILD_NUMBER"
      CUDA_VISIBLE_DEVICES: "-1"
    commands:
      - "rm -rf $JULIA_DEPOT_PATH"
    agents:
      queue: Oceananigans
      architecture: CPU
