agents:
  queue: central
  slurm_mem: 8G # Note that the tests run on shared nodes, so limiting the memory usage might help in avoiding long queues
  modules: climacommon/2025_07_30

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default:"
  OPENBLAS_NUM_THREADS: 1
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  JULIA_NUM_PRECOMPILE_TASKS: 8
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  MPI_TEST: "true"

steps:
  - label: "initialize"
    key: "init_central"
    env:
      TEST_GROUP: "init"
      TEST_ARCHITECTURE: "GPU"
      MPI_TEST: "false" # initialization is not an MPI test
    command:
      - echo "--- Initialize distributed tests"
      - "julia -O0 --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 1
      slurm_gpus_per_task: 1

  - wait

  - label: "🐉 cpu unit tests"
    key: "distributed_cpu"
    env:
      TEST_GROUP: "distributed"
      TEST_ARCHITECTURE: "CPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🐲 gpu unit tests"
    key: "distributed_gpu"
    env:
      TEST_GROUP: "distributed"
      TEST_ARCHITECTURE: "GPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
      slurm_gpus_per_task: 1
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🦾 cpu solvers tests"
    key: "distributed_solvers_cpu"
    env:
      TEST_GROUP: "distributed_solvers"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🛸 gpu solvers tests"
    key: "distributed_solvers_gpu"
    env:
      TEST_GROUP: "distributed_solvers"
      TEST_ARCHITECTURE: "GPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
      slurm_gpus_per_task: 1
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🤿 cpu hydrostatic regression tests 1"
    key: "distributed_hydrostatic_regression_cpu_1"
    env:
      TEST_GROUP: "distributed_hydrostatic_regression_1"
      TEST_ARCHITECTURE: "CPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    timeout_in_minutes: 1440
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🥽 gpu hydrostatic regression tests 1"
    key: "distributed_hydrostatic_regression_gpu_1"
    env:
      TEST_GROUP: "distributed_hydrostatic_regression_1"
      TEST_ARCHITECTURE: "GPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    timeout_in_minutes: 1440
    agents:
      slurm_mem: 100G # Apparently the GPU tests require more memory
      slurm_ntasks: 4
      slurm_gpus_per_task: 1
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "❤️‍🔥 cpu hydrostatic regression tests 2"
    key: "distributed_hydrostatic_regression_cpu_2"
    env:
      TEST_GROUP: "distributed_hydrostatic_regression_2"
      TEST_ARCHITECTURE: "CPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    timeout_in_minutes: 1440
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🪐 gpu hydrostatic regression tests 2"
    key: "distributed_hydrostatic_regression_gpu_2"
    env:
      TEST_GROUP: "distributed_hydrostatic_regression_2"
      TEST_ARCHITECTURE: "GPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    timeout_in_minutes: 1440
    agents:
      slurm_mem: 100G # Apparently the GPU tests require more memory
      slurm_ntasks: 4
      slurm_gpus_per_task: 1
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🤺 cpu hydrostatic model tests"
    key: "distributed_hydrostatic_model_cpu"
    env:
      TEST_GROUP: "distributed_hydrostatic_model"
      TEST_ARCHITECTURE: "CPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    timeout_in_minutes: 1440
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🦏 gpu hydrostatic model tests"
    key: "distributed_hydrostatic_model_gpu"
    env:
      TEST_GROUP: "distributed_hydrostatic_model"
      TEST_ARCHITECTURE: "GPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    timeout_in_minutes: 1440
    agents:
      slurm_mem: 150G # Apparently the GPU tests require more memory?
      slurm_ntasks: 4
      slurm_gpus_per_task: 1
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  # TODO: these tests fail at the moment. Fix them...
  # - label: "🪰 cpu vertical coordinate tests"
  #   key: "distributed_vertical_coordinate_cpu"
  #   env:
  #     TEST_GROUP: "distributed_vertical_coordinate"
  #     TEST_ARCHITECTURE: "CPU"
  #   commands:
  #     - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
  #   timeout_in_minutes: 5440
  #   agents:
  #     slurm_mem: 50G
  #     slurm_ntasks: 4
  #   retry:
  #     automatic:
  #       - exit_status: 1
  #         limit: 1

  # - label: "🪲 gpu vertical coordinate tests"
  #   key: "distributed_vertical_coordinate_gpu"
  #   env:
  #     TEST_GROUP: "distributed_vertical_coordinate"
  #     TEST_ARCHITECTURE: "GPU"
  #   commands:
  #     - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
  #   timeout_in_minutes: 5440
  #   agents:
  #     slurm_mem: 150G # Apparently the GPU tests require more memory?
  #     slurm_ntasks: 4
  #     slurm_gpus_per_task: 1
  #   retry:
  #     automatic:
  #       - exit_status: 1
  #         limit: 1

  - label: "🦍 cpu nonhydrostatic regression"
    key: "distributed_nonhydrostatic_regression_cpu"
    env:
      TEST_GROUP: "distributed_nonhydrostatic_regression"
      TEST_ARCHITECTURE: "CPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - label: "🕺 gpu nonhydrostatic regression"
    key: "distributed_nonhydrostatic_regression_gpu"
    env:
      TEST_GROUP: "distributed_nonhydrostatic_regression"
      TEST_ARCHITECTURE: "GPU"
    commands:
      - "srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
      slurm_gpus_per_task: 1
    retry:
      automatic:
        - exit_status: 1
          limit: 1

  - wait

  - label: ":chart_with_downwards_trend: build history"
    command:
      - "build_history staging"
    artifact_paths:
      - "build_history.html"
