agents:
  queue: central
  slurm_mem: 8G
  modules: climacommon/2025_07_30

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default:"
  OPENBLAS_NUM_THREADS: 1
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  JULIA_NUM_PRECOMPILE_TASKS: 8
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  MPI_TEST: "true"

definitions:
  test_groups: &test_groups
    - "🐉 distributed"
    - "🦾 distributed_solvers"
    - "🤿 distributed_hydrostatic_regression"
    - "🤺 distributed_hydrostatic_model"
    - "🦍 distributed_nonhydrostatic_regression"
    - "🪰 distributed_vertical_coordinate"

  retry_config: &retry_config
    automatic:
      - exit_status: 1
        limit: 1

  test_command: &test_command |
    group="{{ matrix.group }}"
    export TEST_GROUP="\${group#* }"
    srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'

steps:
  - label: "initialize"
    key: "init_central"
    env:
      TEST_GROUP: "init"
      TEST_ARCHITECTURE: "GPU"
      MPI_TEST: "false"
    command:
      - echo "--- Initialize distributed tests"
      - "julia -O0 --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 1
      slurm_gpus_per_task: 1

  - wait

  - label: "CPU - {{ matrix.group }} tests"
    key: "distributed_tests_cpu"
    env:
      TEST_ARCHITECTURE: "CPU"
    command: *test_command
    timeout_in_minutes: 5440
    agents:
      slurm_mem: 100G
      slurm_ntasks: 4
    retry: *retry_config
    matrix:
      setup:
        group: *test_groups

  - label: "GPU - {{ matrix.group }} tests"
    key: "distributed_tests_gpu"
    env:
      TEST_ARCHITECTURE: "GPU"
    command: *test_command
    timeout_in_minutes: 5440
    agents:
      slurm_mem: 150G
      slurm_ntasks: 4
      slurm_gpus_per_task: 1
    retry: *retry_config
    matrix:
      setup:
        group: *test_groups

  - wait

  - label: ":chart_with_downwards_trend: build history"
    command:
      - "build_history staging"
    artifact_paths:
      - "build_history.html"
