agents:
  queue: central
  slurm_mem: 8G # Note that the tests run on shared nodes, so limiting the memory usage might help in avoiding long queues
  modules: climacommon/2025_07_30

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default:"
  OPENBLAS_NUM_THREADS: 1
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
  JULIA_NUM_PRECOMPILE_TASKS: 8
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  MPI_TEST: "true"

steps:
  - label: "initialize"
    key: "init_central"
    env:
      TEST_GROUP: "init"
      TEST_ARCHITECTURE: "GPU"
      MPI_TEST: "false" # initialization is not an MPI test
    command:
      - echo "--- Initialize distributed tests"
      - "julia -O0 --project -e 'using Pkg; Pkg.test()'"
    agents:
      slurm_mem: 50G
      slurm_ntasks: 1
      slurm_gpus_per_task: 1

  - wait

  - label: "{{ matrix.architecture }} - {{ matrix.group }} tests"
    key: "distributed_tests"
    command: |
      # Set architecture-specific environment variables
      if [[ "{{ matrix.architecture }}" == "CPU" ]]; then
        export TEST_ARCHITECTURE="CPU"
      else
        export TEST_ARCHITECTURE="GPU"
      fi

      # Strip emoji for environment variable
      group="{{ matrix.group }}"
      export TEST_GROUP="${group#* }"

      srun julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'
    timeout_in_minutes: 5440
    agents:
      slurm_mem: 50G
      slurm_ntasks: 4
    retry:
      automatic:
        - exit_status: 1
          limit: 1

    matrix:
      setup:
        architecture:
          - "CPU"
          - "GPU"
        group:
          - "🐉 distributed"
          - "🦾 distributed_solvers"
          - "🤿 distributed_hydrostatic_regression"
          - "🤺 distributed_hydrostatic_model"
          # - "🪰 distributed_vertical_coordinate"
          - "🦍 distributed_nonhydrostatic_regression"

      adjustments:
        # GPU tests need GPUs
        - with:
            architecture: "GPU"
          agents:
            slurm_gpus_per_task: 1

        # GPU hydrostatic regression needs more memory
        - with:
            architecture: "GPU"
            group: "🤿 distributed_hydrostatic_regression"
          agents:
            slurm_mem: 100G

        # GPU hydrostatic model needs more memory
        - with:
            architecture: "GPU"
            group: "🤺 distributed_hydrostatic_model"
          agents:
            slurm_mem: 150G

        # # GPU vertical coordinate needs more memory
        # - with:
        #     architecture: "GPU"
        #     group: "🪰 distributed_vertical_coordinate"
        #   agents:
        #     slurm_mem: 150G

  - wait

  - label: ":chart_with_downwards_trend: build history"
    command:
      - "build_history staging"
    artifact_paths:
      - "build_history.html"
