name: Dependency Checks

on:
  pull_request:
    paths:
      - '.github/workflows/dependency_checks.yml'
      - 'test/Project.toml'
      - 'benchmarks/Project.toml'
      - 'Project.toml'
  push:
    branches:
      - main
    tags: '*'
    paths:
      - '.github/workflows/dependency_checks.yml'
      - 'test/Project.toml'
      - 'benchmarking/Project.toml'
      - 'Project.toml'
jobs:
  check_minimum_version:
    name: Check Minimum Dependency Versions
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        downgrade_mode: ['deps', 'alldeps']
        version:
          - '1.11.9'
        os:
          - ubuntu-latest
        arch:
          - x64
        dir:
          - './'
          - 'test/'
          - 'benchmarking/'
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-downgrade-compat@v2
        with:
          mode: ${{ matrix.downgrade_mode }}
      - run: cd ${{ matrix.dir }}
      - run: julia --color=yes -e 'import Pkg; Pkg.Registry.update()'
      - run: julia --color=yes -e 'import Pkg; Pkg.activate("./"); Pkg.resolve()'
  resolve_dependencies:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11.9'
        os:
          - ubuntu-latest
        arch:
          - x64
        dir:
          - 'test/'
          - 'benchmarking/'
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: cd ${{ matrix.dir }}
      - run: julia --color=yes -e 'import Pkg; Pkg.Registry.update()'
      - run: julia --color=yes -e 'import Pkg; Pkg.activate("./"); Pkg.resolve()'
